title = "Zonge International"
baseURL = "https://zonge-international.github.io/HugoWebsite/"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true
relativeURLs = true
canonifyURLs = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
title = "Zonge International"
# languageDirection = 'rtl' for Right-To-Left languages


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "Zonge International" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = "/images/logo.png"
description = "EM Geophysics"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-blue"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-blue-80"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]

[params.ananke.social.linkedin]
profilelink = "https://www.linkedin.com/company/zonge-international/"

